from typing import Protocol

from .types import DispatchInput


class CommandQueueService(Protocol):
    def enqueue_commands(self, session, cmds: list[str]) -> None: ...
    def cancel_batch(self, session, batch_id: str) -> None: ...
    def next_input(self, session) -> DispatchInput | None: ...
    def has_pending(self, session) -> bool: ...
