import re


def format_codes_to_ansi(text: str) -> str:
    """
    Converts inline formatting codes (e.g., |r, |B, |n) to ANSI escape sequences.

    Common in MUD-style output or Telnet-compatible formatting.
    Supports colors, bold, underline, and reset.

    Args:
        text (str): The input string containing inline format codes.

    Returns:
        str: The same string with ANSI sequences applied.
    """

    return (
        text.replace("|c", "\x1b[36m")  # cyan
        .replace("|w", "\x1b[37m")  # white
        .replace("|r", "\x1b[31m")  # red
        .replace("|g", "\x1b[32m")  # green
        .replace("|y", "\x1b[33m")  # yellow
        .replace("|b", "\x1b[34m")  # blue
        .replace("|m", "\x1b[35m")  # magenta
        .replace("|d", "\x1b[90m")  # dark gray
        .replace("|B", "\x1b[1m")  # bold
        .replace("|u", "\x1b[4m")  # underline
        .replace("|h", "\x1b[7m")  # inverse
        .replace("|n", "\x1b[0m")  # reset
    )


def strip_ansi_formats(text: str) -> str:
    """
    Removes ANSI escape sequences from a string,
    such as those generated by format_codes_to_ansi().

    Useful for converting styled output back to plain text
    (e.g., for Telnet fallback, logs, or diffing).

    Args:
        text (str): The string containing ANSI escape sequences.

    Returns:
        str: Clean string without ANSI codes.
    """

    ansi_escape = re.compile(r"\x1b\[[0-9;]*[mK]")
    return ansi_escape.sub("", text)
