from __future__ import annotations

from typing import Protocol

from yakoon.base.values.key import Key

from .session import CommandSession


class SessionService(Protocol):
    async def delete_by_key(self, key: Key): ...
    async def get(self, key: Key) -> CommandSession: ...
    async def get_or_create(
        self, key: Key, **kwargs
    ) -> tuple[CommandSession, bool]: ...
    async def save(self, session: CommandSession) -> None: ...

    def release(self, key: Key) -> None: ...
    def clear(self) -> None: ...
