from typing import Protocol


class AuditLogService(Protocol):
    def audit(self, msg: str): ...
    def warning(self, message: str, session): ...
    def error(self, *, error: Exception, session=None): ...
    def security(self, session, obj, action): ...
