from __future__ import annotations

from typing import Protocol

from ..models import Box, World


class WorldService(Protocol):

    async def list_worlds(self) -> list[World]: ...

    async def add_world(self, *, name: str, description: str) -> World: ...

    async def get_world(self, world_id: str) -> World | None: ...

    async def get_world_by_name(self, name: str) -> World | None: ...

    async def update_world(self, *, world_id: str, name: str | None, description: str | None, entry_box_id: str | None = None) -> World: ...

    async def delete_world(self, world_id: str) -> None: ...

    async def set_entry(self, *, world_id: str, box_id: str) -> World: ...


class BoxService(Protocol):

    async def add_box(self, *, world_id: str, parent_id: str | None, name: str, description: str) -> Box: ...

    async def get_box(self, box_id: str) -> Box | None: ...

    async def list_boxes(self, *, world_id: str, parent_id: str | None) -> list[Box]: ...

    async def update_box(self, *, box_id: str, name: str, description: str) -> Box: ...

    async def delete_box(self, box_id: str) -> None: ...
