from __future__ import annotations

from typing import Protocol

from ..models import Box, Exit, Note, NoteLink, World


class WorldService(Protocol):

    async def list_worlds(self) -> list[World]: ...
    async def add_world(self, *, name: str, description: str) -> World: ...
    async def get_world(self, world_id: str) -> World | None: ...
    async def get_world_by_name(self, name: str) -> World | None: ...
    async def update_world(self, *, world_id: str, name: str | None, description: str | None, entry_box_id: str | None = None) -> World: ...
    async def delete_world(self, world_id: str) -> None: ...
    async def set_entry(self, *, world_id: str, box_id: str) -> World: ...


class BoxService(Protocol):

    async def add_box(self, *, world_id: str, parent_id: str | None, name: str, description: str, portable: bool = False) -> Box: ...
    async def get_box(self, box_id: str) -> Box | None: ...
    async def list_boxes(self, *, world_id: str, parent_id: str | None) -> list[Box]: ...
    async def update_box(self, *, box_id: str, name: str, description: str) -> Box: ...
    async def delete_box(self, box_id: str) -> None: ...
    async def move_box(self, box_id: str, new_parent_id: str | None) -> Box: ...
    async def find_box(self, *, world_id: str, name: str) -> Box | None: ...


class ExitService(Protocol):

    async def get_exit(self, exit_id: str) -> Exit | None: ...
    async def list_exits(self, *, world_id: str) -> list[Exit]: ...
    async def find_from(self, box_id: str) -> list[Exit]: ...
    async def find_to(self, box_id: str) -> list[Exit]: ...
    async def connect(self, *, world_id: str, source_box_id: str, target_box_id: str, name: str, description: str = "", direction: str = "") -> Exit: ...
    async def disconnect(self, exit_id: str) -> None: ...


class NoteService(Protocol):

    async def add_note(self, *, name: str, content: str) -> Note: ...
    async def get_note(self, note_id: str) -> Note | None: ...
    async def find_note_by_name(self, name: str) -> Note | None: ...
    async def update_note(self, *, note_id: str, name: str, content: str) -> Note: ...
    async def delete_note(self, note_id: str) -> None: ...
    async def list_notes(self) -> list[Note]: ...
    async def inbox(self) -> list[Note]: ...
    async def link(self, *, note_id: str, box_id: str) -> NoteLink: ...
    async def unlink(self, note_id: str, box_id: str) -> None: ...
    async def links_for_box(self, box_id: str) -> list[NoteLink]: ...
    async def notes_for_box(self, box_id: str) -> list[Note]: ...
