from typing import Protocol

from yakoon.base.capabilities.identity import Account, AuthResult
from yakoon.base.runtime.sessions import Session
from yakoon.base.values import Key, Namespace


class SecretVerifier(Protocol):
    def verify(self, account: Account, secret: str) -> bool: ...


class AuthenticationService(Protocol):
    async def authenticate(
        self, namespace: Namespace, username: str, secret: str
    ) -> AuthResult: ...


class PermissionService(Protocol):

    def register_role(self, name: str, specs: list[str]) -> None: ...
    def set_bootstrap_permissions(self, session: Session): ...
    def apply_account_permissions(self, session: Session, account: Account): ...
    def can_execute(self, session: Session, perm_key: str) -> bool: ...
    def can_read(self, session: Session, perm_key: str) -> bool: ...


class AccountService(Protocol):

    async def get_by_key(self, key: Key) -> Account | None: ...
    async def get_by_username(
        self, namespace: Namespace, name: str
    ) -> Account | None: ...
    async def save(self, account: Account): ...
    async def delete_by_key(self, key: Key): ...
