from enum import IntEnum


class ExecStep(IntEnum):
    EXECUTION_START = 1

    COMMAND_RECEIVED = 10
    COMMAND_RESOLVED = 11
    COMMAND_PREPARED = 12
    COMMAND_RUNNING = 13
    COMMAND_SUCCESS = 14
    COMMAND_FAILED = 15

    # TODO: Later
    # WORKFLOW_START = 20
    # WORKFLOW_FINISH = 21
