system:
  backend: sqlite
  db_path: db/system.sqlite3.db
  script_path: yakoon/bootstrap/stores/sqlite

gateway:
  backend: sqlite
  db_path: db/gateway.sqlite3.db
  script_path: yakoon/domains/gateway/stores/sqlite/scripts


#account:
#  backend: postgres
#  dsn: postgresql://...
