# runner.py
from __future__ import annotations

from typing import Protocol

from yakoon.base.models.prompt import PromptMode

class HostAdapter(Protocol):
    async def on_prompt(self, *, prompt: str, mode: PromptMode) -> None: ...
    async def on_ready(self, *, prompt: str) -> None: ...
    async def on_idle(self) -> None: ...
    async def on_exit(self) -> None: ...