from collections.abc import Sequence
from typing import Protocol

from yakoon.base.commands import CommandKind
from yakoon.base.runtime.sessions import Session

from .info import AppInfo, CommandInfo


class ApplicationQuery(Protocol):
    def ids(self) -> Sequence[str]: ...
    def all(self) -> Sequence[AppInfo]: ...

    def shell(self) -> AppInfo: ...
    def get(self, app_id: str) -> AppInfo | None: ...
    def has(self, app_id: str) -> bool: ...

    def activatable(self) -> Sequence[AppInfo]: ...
    def listed(self) -> Sequence[AppInfo]: ...
    def is_shell(self, app_id: str) -> bool: ...
    def is_activatable(self, app_id: str) -> bool: ...
    def is_listed(self, app_id: str) -> bool: ...


class CommandQuery(Protocol):
    def build(self) -> None: ...
    def all(self) -> tuple[CommandInfo, ...]: ...
    def globals(self) -> tuple[CommandInfo, ...]: ...

    def for_app(self, app_id: str) -> Sequence[CommandInfo]: ...
    def for_app_visible(
        self, app_id: str, session: Session
    ) -> Sequence[CommandInfo]: ...
    def for_resolve_context(
        self,
        app_id: str,
    ) -> tuple[CommandInfo, ...]: ...
    def for_man_entries(
        self,
        app_id: str,
        session: Session,
        mode: str,
        kind_filter: CommandKind | None = None,
    ) -> Sequence[CommandInfo]: ...
    def for_context(
        self,
        app_id: str,
        command_key: str,
    ) -> CommandInfo | None: ...
