from collections.abc import Sequence
from typing import Protocol

from yakoon.base.catalogs import CommandInfo, ControllerInfo
from yakoon.base.runtime import CommandKind, Session


class CommandCatalogService(Protocol):
    def build(self) -> None: ...
    def all(self) -> tuple[CommandInfo, ...]: ...
    def for_controller(self, controller_id: str) -> Sequence[CommandInfo]: ...
    def for_controller_visible(
        self, controller_id: str, session: Session
    ) -> Sequence[CommandInfo]: ...
    def for_resolve_context(
        self,
        controller_id: str,
    ) -> tuple[CommandInfo, ...]: ...
    def for_man_entries(
        self,
        controller_id: str,
        session: Session,
        mode: str,
        kind_filter: CommandKind | None = None,
    ) -> Sequence[CommandInfo]: ...
    def resolve_info(
        self,
        controller_id: str,
        command_key: str,
    ) -> CommandInfo | None: ...


class ControllerCatalogService(Protocol):
    def ids(self) -> Sequence[str]: ...
    def all(self) -> Sequence[ControllerInfo]: ...
    def get(self, controller_id: str) -> ControllerInfo | None: ...
    def exists(self, controller_id: str) -> bool: ...
    def activatable(self) -> Sequence[ControllerInfo]: ...
    def listed(self) -> Sequence[ControllerInfo]: ...
    def shell(self) -> Sequence[ControllerInfo]: ...
    def is_shell(self, controller_id: str) -> bool: ...
    def is_activatable(self, controller_id: str) -> bool: ...
    def is_listed(self, controller_id: str) -> bool: ...
