#:kivy 2.2.0
#:import theme yakoon.kivy.themes.active.active_theme

<StreamLabel@Label>:
    #

<TextBlockWidget>:
    font_name: theme.font
    color: theme.text

    halign: "left"
    valign: "top"

    size_hint_y: None

    canvas.before:
        Color:
            rgba: 0.6, 0.3, 0.3, 0.5
        Line:
            width: 1
            rectangle: (self.x, self.y, self.width, self.height)
        RoundedRectangle:
            pos: self.pos
            size: self.size