kind: command_view

views:

  success:
    title: 
    role: info
    blocks:
      - type: text
        text: su {{data.user}}

  failed:
    title: 
    role: error
    blocks:
      - type: text
        text: "No! Reason: {{data.reason}}"  

inputs: 

  ask_user:
    fields:
      - { var: auth.user, policy: system:string, title: "Username" } 

  ask_secret:
    fields:
      - { var: auth.password, policy: system:masked, title: "Password"} 
