kind: command_view

views:

  show_user:
    title: 
    role: info
    blocks:
      - type: text
        text: {{section.data.user}}

  show_hint:
    title: 
    role: info
    blocks:
      - type: text
        text: use 'su' to login

inputs: {}
