
<CommandMessage>:
    size_hint_y: None
    size_hint_x: 1

    #orientation: "lr-tb"   # wichtig: top-down
    orientation: "vertical"
    
    text_size: self.width, None

    #padding: dp(10), dp(8)

    #canvas.before:
    #    Color:
    #        rgba: 0.4, 0.5, 0.5, 0.5
    #    Line:
    #        width: 1
    #        rectangle: (self.x, self.y, self.width, self.height)
    #    RoundedRectangle:
    #        pos: self.pos
    #       size: self.size
