from typing import Protocol
from mygame.models.character import Character

class CharacterStoreProtocol(Protocol):
    def get(cls, char_id: str) -> Character | None: ...
    def put(cls, obj: Character) -> None: ...
    def all(cls) -> list[Character]: ...
    def exists(self, char_id: str) -> bool: ...
