from typing import Optional, Protocol
from mygame.models.object import Object

class ObjectStoreProtocol(Protocol):
    def get(cls, obj_id: str) -> Optional[Object]: ...
    def put(cls, obj: Object) -> None: ...
    def contents_of(cls, location_id: str) -> list[Object]: ...
