from typing import Protocol, Iterable


class Prompts(Protocol):
    async def ask(self, key: str) -> str: ...
    async def choice(self, key: str, options: Iterable[str]) -> str: ...
    async def confirm(self, key: str) -> bool: ...
