#:import dp kivy.metrics.dp
#:import theme yakoon.kivy.themes.active.active_theme

<TabViewPage>:
    orientation: "vertical"
    padding: dp(theme.pad), dp(theme.pad)
    spacing: dp(theme.pad)
    canvas.before:
        Color:
            rgba: theme.surface_input
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [dp(theme.radius)]


    BoxLayout:
        id: content_host
        orientation: "vertical"
        size_hint_y: 1
