kind: command_view

views:

  show_help:
    title: 
    role: info
    blocks:
      - type: text
        text: >  
          {%- if data.mode == "shell" -%}
          Commands: {{ "\n" }}
          {{ data.shell_commands | map(attribute='key') | join('  ') }}
          {{ "\n" -}}
          Available programs: {{ "\n" }}
          {{ data.controllers | map(attribute='id') | join('  ') }}          
          {%- elif data.mode == "program" -%}
          Commands:
          {{ data.commands | map(attribute='key') | join('  ') }}
          {% endif %}

  no_manual_entry:
    role: info
    title: 
    blocks:
      - type: text
        text: No manual entry for {{data.command_key}}

  man_page:
    role: info
    title: 
    blocks:
      - type: text
        text: Manual comming soon ....

inputs: {}