kind: command_view

views:

  show:
    role: info
    title: 
    blocks:
      - type: text
        text: > 
          {{ data.controllers | map(attribute='id') | join('  ') }}

  name_not_found:
    role: error
    title: 
    blocks:
      - type: text
        text: Das Programm "{{data.name}}" wurde nicht gefunden.

  already_in_shell:
    role: info
    title: 
    blocks:
      - type: text
        text: Programm "{{data.controller.id}}" ist bereits aktiv.

inputs: {}
