from __future__ import annotations

import asyncio
from collections.abc import Awaitable, Callable, Mapping, Sequence
from enum import StrEnum
from typing import Any, Protocol

from yakoon.base.models.account import Account, AuthResult
from yakoon.base.models.catalog import CommandInfo, ControllerInfo
from yakoon.base.models.command import CommandKind
from yakoon.base.models.input import DispatchInput
from yakoon.base.models.key import Key
from yakoon.base.models.message import MessageSpec
from yakoon.base.models.ns import Namespace
from yakoon.base.models.policy import (
    FieldPolicy,
    PolicyValidationResult,
    RawValue,
)
from yakoon.base.models.prompt import PromptResult
from yakoon.base.models.view import ViewSpec
from yakoon.base.models.workflow import StepDef, WorkflowDef, WorkflowRuntime
from yakoon.base.plugins.plugin import PluginMeta
from yakoon.base.runtime.session.session import Session
from yakoon.platform.runtime.render.context import RenderContext
from yakoon.platform.runtime.render.section import RenderSection


class ViewSpecService(Protocol):
    def parse_spec(self, yaml_text: str) -> ViewSpec: ...


class MessageSpecService(Protocol):
    async def parse_spec(self, yaml_text: str) -> MessageSpec: ...


class PolicyService(Protocol):
    def register_policy(self, policy: FieldPolicy) -> None: ...
    def register_policies(self, policies: list[FieldPolicy]) -> None: ...
    def get_policy(self, key: str) -> FieldPolicy: ...
    def register_validator(self, key: str, fn) -> None: ...
    def get_validator(self, key: str) -> Callable: ...
    def register_defaults(self) -> None: ...
    def validate(self, *, policy_key: str, raw: RawValue) -> PolicyValidationResult: ...


class WorkflowService(Protocol):
    def runtime(self, session: Any) -> WorkflowRuntime: ...

    def enqueue_next(self, session: Any, batch_id: str) -> None: ...
    def complete_input_step(
        self,
        session,
        *,
        batch_id: str,
        step_id: str,
        values: Mapping[str, Any],
        ignore_none: bool = True,
    ) -> None: ...

    def complete_run_step(
        self, session: Any, *, batch_id: str, step_id: str
    ) -> None: ...

    def set_value(self, session: Any, batch_id: str, key: str, value: Any) -> None: ...
    def get_def(self, controller_id: str, command_key: str) -> WorkflowDef: ...
    def get_step(self, session: Any, batch_id: str, step_id: str) -> StepDef: ...

    def fail_batch(
        self,
        session,
        *,
        batch_id: str,
        code: str,
        message: str,
        command: str | None = None,
    ) -> None: ...
    def cancel_batch(self, session, *, batch_id: str) -> None: ...

    def start(
        self,
        session,
        controller_id: str,
        command_key: str,
        *,
        enqueue_first: bool = True,
    ) -> str: ...
    def start_with_values(
        self,
        session,
        controller_id: str,
        command_key: str,
        values: Mapping[str, Any],
        *,
        enqueue_first: bool = True,
        ignore_none: bool = True,
    ) -> str: ...
    def resume_with_values(
        self,
        session,
        batch_id: str,
        values: Mapping[str, Any],
        *,
        ignore_none: bool = True,
        enqueue_next: bool = True,
    ) -> None: ...


class WorkflowCompileService(Protocol):
    def load_def(self, source: Any, command_key: str) -> WorkflowDef: ...


class DialogState(StrEnum):
    IDLE = "idle"
    WAITING_WIZARD = "waiting_wizard"
    WAITING_FORM = "waiting_form"


class InputService(Protocol):

    async def ask_view(self, session: Session, field: ViewSpec) -> PromptResult: ...


class DialogService(Protocol):

    def state(self, session: Session) -> DialogState: ...
    def edge_event(self, session: Session) -> asyncio.Event: ...

    def resolve_input(self, session: Session, values: dict[str, object]) -> bool: ...
    def cancel_input(self, session: Session) -> None: ...
    def cleanup(self, session: Session) -> None: ...

    def is_waiting(self, session: Session) -> bool: ...
    def get_view(self, session: Session) -> ViewSpec: ...
    def wait_view(
        self,
        session: Session,
        *,
        view: ViewSpec,
        timeout: float | None = None,
        on_timeout: Callable[[], Awaitable[None]] | None = None,
    ) -> asyncio.Future: ...


class CommandQueueService(Protocol):
    def enqueue_commands(self, session, cmds: list[str]) -> None: ...
    def cancel_batch(self, session, batch_id: str) -> None: ...
    def next_input(self, session) -> DispatchInput | None: ...
    def has_pending(self, session) -> bool: ...


class SecretVerifier(Protocol):
    def verify(self, account: Account, secret: str) -> bool: ...


class AuthenticationService(Protocol):
    async def authenticate(
        self, namespace: Namespace, username: str, secret: str
    ) -> AuthResult: ...


class PermissionService(Protocol):

    def register_role(self, name: str, specs: list[str]) -> None: ...
    def set_bootstrap_permissions(self, session: Session): ...
    def apply_account_permissions(self, session: Session, account: Account): ...
    def can_execute(self, session: Session, perm_key: str) -> bool: ...
    def can_read(self, session: Session, perm_key: str) -> bool: ...


class AccountService(Protocol):

    async def get_by_key(self, key: Key) -> Account | None: ...
    async def get_by_username(
        self, namespace: Namespace, name: str
    ) -> Account | None: ...
    async def save(self, account: Account): ...
    async def delete_by_key(self, key: Key): ...


class CommandCatalogService(Protocol):
    def for_controller(self, controller_id: str) -> Sequence[CommandInfo]: ...
    def for_controller_visible(
        self, controller_id: str, session: Session
    ) -> Sequence[CommandInfo]: ...
    def for_man_entries(
        self,
        controller_id: str,
        session: Session,
        mode: str,
        kind_filter: CommandKind | None = None,
    ) -> Sequence[CommandInfo]: ...
    def keys_for_controller(self, controller_id: str) -> Sequence[str]: ...
    def is_shell_builtin(self, key: str) -> bool: ...
    def shell_builtins(self) -> Sequence[str]: ...


class ControllerCatalogService(Protocol):
    def ids(self) -> Sequence[str]: ...
    def all(self) -> Sequence[ControllerInfo]: ...
    def get(self, controller_id: str) -> ControllerInfo | None: ...
    def exists(self, controller_id: str) -> bool: ...
    def activatable(self) -> Sequence[ControllerInfo]: ...
    def listed(self) -> Sequence[ControllerInfo]: ...
    def shell(self) -> Sequence[ControllerInfo]: ...
    def is_shell(self, controller_id: str) -> bool: ...
    def is_activatable(self, controller_id: str) -> bool: ...
    def is_listed(self, controller_id: str) -> bool: ...


class ShardedCounterService(Protocol):
    async def next(self, prefix: str) -> str: ...


class SessionService(Protocol):
    async def delete_by_key(self, key: Key): ...
    async def get(self, key: Key) -> Session: ...
    async def get_or_create(self, key: Key, **kwargs) -> tuple[Session, bool]: ...
    async def save(self, session: Session) -> None: ...

    def release(self, key: Key) -> None: ...
    def clear(self) -> None: ...


class RendererService(Protocol):
    async def render_text(self, ctx: RenderContext, key: str, **data) -> str: ...
    async def render_view(self, ctx: RenderContext, key: str, **data) -> ViewSpec: ...
    async def render_spec(
        self, ctx: RenderContext, key: str, **data
    ) -> MessageSpec: ...


class NamespaceService(Protocol):
    async def from_session(self, session: Session) -> Namespace: ...
    async def get_by_bucket(
        self, bucket: str = "bucket", scope: str = "develop"
    ) -> Namespace: ...


class AuditLogService(Protocol):
    async def audit(self, msg: str): ...
    async def error(self, exc: Exception): ...
    async def permission(self, session, obj, action): ...


class TemplateLoader(Protocol):

    async def load(self, ctx: RenderContext) -> str: ...


class RenderEngine(Protocol):

    async def render_str(self, template_str: str, *, section: RenderSection) -> str: ...
    async def render_any(self, obj: Any, *, section: RenderSection) -> Any: ...


class PresenterViews(Protocol):
    async def emit(self, section_key: str, **data) -> None: ...


class PresenterInputs(Protocol):
    async def ask(self, section_key: str, **data) -> PromptResult: ...


class Presenter(Protocol):

    inputs: PresenterInputs
    views: PresenterViews


class PresenterService(Protocol):
    async def create_presenter(
        self, template_prefix: str, template_key: str, session: Session
    ) -> Presenter: ...


class IO(Protocol):
    async def view(self, view: ViewSpec) -> None: ...


class PluginRegistry(Protocol):
    def register(self, meta: PluginMeta) -> None: ...
    def list(self) -> list[PluginMeta]: ...
