from typing import Protocol

from yakoon.base.projection.view import View

from .types import DispatchInput


class CommandQueueService(Protocol):
    def enqueue_commands(self, session, cmds: list[str]) -> None: ...
    def cancel_batch(self, session, batch_id: str) -> None: ...
    def next_input(self, session) -> DispatchInput | None: ...
    def has_pending(self, session) -> bool: ...


class Interaction(Protocol):

    async def show_prompt(self, ps1: str) -> None: ...
    async def show_view(self, view: View) -> None: ...
    async def exit(self) -> None: ...
