from typing import Any, Protocol

from y5n.base.naming import Key
from y5n.base.permissions import PermissionSet
from y5n.base.runtime.input import Interaction


class Session(Protocol):

    @property
    def lang(self) -> str: ...

    @property
    def key(self) -> Key: ...

    @property
    def permissions(self) -> PermissionSet: ...
    def set_permissions(self, permset: PermissionSet) -> None: ...

    def set_identity(self, user_key, user_name: str | None = None) -> None: ...
    def get_identity(self) -> Key | None: ...
    def get_identity_name(self) -> str | None: ...

    @property
    def interaction(self) -> Interaction: ...
    @interaction.setter
    def interaction(self, value: Interaction) -> None: ...

    def get_data(self, key: str, default: Any = None) -> Any: ...
    def set_data(self, key: str, value: Any) -> None: ...
    def del_data(self, key: str, default: Any = None) -> Any: ...
