class Terminal:

    def write(self, text: str): ...
    def clear(self): ...
    def set_prompt(self, field): ...
    def reset_prompt(self): ...
    def new_line(self): ...
    def notify_ready(self): ...
