from __future__ import annotations

from collections.abc import Callable
from typing import Protocol

from .policy import FieldPolicy, FieldPolicyValidationResult, RawValue


class FieldPolicyEngine(Protocol):
    def register_policy(self, policy: FieldPolicy) -> None: ...
    def register_policies(self, policies: list[FieldPolicy]) -> None: ...
    def get_policy(self, key: str) -> FieldPolicy: ...
    def register_validator(self, key: str, fn) -> None: ...
    def get_validator(self, key: str) -> Callable: ...
    def register_defaults(self) -> None: ...
    def validate(
        self, *, policy_key: str, raw: RawValue
    ) -> FieldPolicyValidationResult: ...
